In [1]:
import numpy as np


In [10]:
arr=[[1,2],[3,4]]
print(arr)

[[1, 2], [3, 4]]


In [5]:
#convert to numpy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [6]:
import torch

In [7]:
#convert to pytorch tensor
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

#### creat matrix with default values

In [13]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [14]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [16]:
np.random.rand(2,2)


array([[0.42915481, 0.65587207],
       [0.16954481, 0.05817896]])

In [17]:
torch.rand(2,2)

tensor([[0.0794, 0.0319],
        [0.5934, 0.3263]])

In [18]:
#seeds for reproducibility
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [19]:
#seed 
np.random.seed(0)
np.random.rand(2,2)


array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [20]:
#no seed
np.random.rand(2,2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [21]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [22]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [23]:
torch.rand(2,2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

In [28]:
# if using gpu..
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

#### numpy and torch Bridge

In [29]:
np_array=np.ones((2,2))

In [30]:
print(np_array)

[[1. 1.]
 [1. 1.]]


In [31]:
print(type(np_array))

<class 'numpy.ndarray'>


In [35]:
#convert to Torch Tensor
torch_tensor=torch.from_numpy(np_array)

In [36]:
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [37]:
print(type(torch_tensor))
#DoubleTensor

<class 'torch.Tensor'>


In [38]:
#how do u get different kind of tensor
np_array_new=np.ones((2,2),dtype=np.int8)
torch.from_numpy(np_array_new)

TypeError: can't convert np.ndarray of type numpy.int8. The only supported types are: double, float, float16, int64, int32, and uint8.

The conversion supports:
    
1.double 
2. float
3. int64, int 32, unit8


In [40]:
np_array_new=np.ones((2,2),dtype=np.int64)
torch.from_numpy(np_array_new)
#longtensor

tensor([[1, 1],
        [1, 1]])

In [41]:
np_array_new=np.ones((2,2),dtype=np.int32)
torch.from_numpy(np_array_new)
#inttensor

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [44]:
np_array_new=np.ones((2,2),dtype=np.uint8)
torch.from_numpy(np_array_new)
#byte tensor

tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)

In [45]:
np_array_new=np.ones((2,2),dtype=np.float64)
torch.from_numpy(np_array_new)
#doubletensor

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [46]:
np_array_new=np.ones((2,2),dtype=np.float32)
torch.from_numpy(np_array_new)
#floattensor

tensor([[1., 1.],
        [1., 1.]])

In [47]:
np_array_new=np.ones((2,2),dtype=np.double)
torch.from_numpy(np_array_new)
#doubletensor

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

#### Torch to numpy

In [48]:
torch_tensor=torch.ones(2,2)


In [49]:
type(torch_tensor)

torch.Tensor

In [52]:
torch_to_numpy=torch_tensor.numpy()

In [53]:
type(torch_to_numpy)

numpy.ndarray

Tensor on CPU vs GPU

In [55]:
#CPU by default
tensor_cpu=torch.ones(2,2)


In [57]:
#CPU to GPU
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [58]:
#GPU to CPU
tensor_cpu.cpu

<function Tensor.cpu>

# Resizing Tensor

In [60]:
a=torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [62]:
print(a.size())
#change it to the 4 rows
a.view(4)

torch.Size([2, 2])


tensor([1., 1., 1., 1.])

In [63]:
a.view(4).size()

torch.Size([4])

# Element_wise Addition

In [64]:

a=torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [65]:
b=torch.ones(2,2)
print(b)

tensor([[1., 1.],
        [1., 1.]])


In [68]:
c=a+b
print(c)
c=torch.add(a,b)
print(c)


tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])


In [73]:
#in place operation
print(a)
print(b)

print(torch.sub(a,b))
print(a)

print(a.sub_(b))
print(a)

#torch.div(b,a)=b/a in place b.div_a
#torch.mul(b,a)





tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[-1., -1.],
        [-1., -1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[-1., -1.],
        [-1., -1.]])
tensor([[-1., -1.],
        [-1., -1.]])


Tensor Mean

In [74]:
#nested list
a= torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.size()

torch.Size([10])

In [75]:
a.mean(dim=0)

tensor(5.5000)

In [85]:
a=torch.Tensor([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
a.size()



torch.Size([2, 10])

In [86]:
a.mean(dim=1)

tensor([5.5000, 5.5000])

In [88]:
a=torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.std(dim=0)

tensor(3.0277)