# Variable

In [7]:
import torch
from torch.autograd import Variable

In [8]:
a=Variable(torch.ones(2,2),requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [10]:
b=Variable(torch.ones(2,2),requires_grad=True)
print(a+b)
print(torch.add(a,b))
print(a*b)
print(torch.mul(a,b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<ThMulBackward>)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<ThMulBackward>)


# 2.2 Gradients


In [13]:
x=Variable(torch.ones(2),requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

In [14]:
y=5*(x+1)**2
y

tensor([20., 20.], grad_fn=<MulBackward>)

In [16]:
# o=1/2 *sum of y
o=(1/2)*torch.sum(y)
o


tensor(20., grad_fn=<MulBackward>)

In [ ]:
yi=5(xi+1)^2
o=1/2 segmai yi
o=1/2 segmai 5(xi+1)^2



