# Variable

In [96]:
import torch
import numpy as np
from torch.autograd import Variable

In [97]:
a=Variable(torch.ones(2,2),requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [98]:
b=Variable(torch.ones(2,2),requires_grad=True)
print(a+b)
print(torch.add(a,b))
print(a*b)
print(torch.mul(a,b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<ThMulBackward>)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<ThMulBackward>)


# 2.2 Gradients


In [99]:
x=Variable(torch.ones(2),requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

In [100]:
y=5*(x+1)**2
y

tensor([20., 20.], grad_fn=<MulBackward>)

In [101]:
# o=1/2 *sum of y
o=(1/2)*torch.sum(y)
o


tensor(20., grad_fn=<MulBackward>)

yi=5(xi+1)^2

o=1/2 segmai yi

o=1/2 segmai 5(xi+1)^2

d(0)/d(xi)=1/2[10*(xi+1)]






In [102]:
o.backward()

In [110]:
x.grad

tensor([10., 10.])

In [109]:
#backward in detail
o.backward(torch.FloatTensor(np.squeeze([1.0])))

x.grad

tensor([10., 10.])

In [108]:
a=np.squeeze([1.0])
print(a)

1.0


In [117]:
X = ','.join( str(a) for a in [1,2,3] )
print(X)


1,2,3
